name: Gitleaks - Scanning Secrets in PR

on:
  pull_request:
    types:
      - synchronize
      - opened
    branches:
      - 'main'
      - 'master'

jobs:
  scan:
    uses: DevSecOps2026/reusable_workflow/.github/workflows/gitleaks_reusable_workflow.yml@main
    secrets:
      GITLEAKS_LICENSE: "test" 
